title: Machine Learning Workflow Orchestration
subtitle: Flyte & StreamFlow
author: Bernd Doser
date: 2024/10/15
date-format: "MMMM YYYY"
institute: "[HITS](https://h-its.org)"

title-slide-attributes:
  data-background-image: images/ai_workflow2.png
  data-background-size: cover
  data-background-opacity: "0.3"

css: styles.css
# theme: league
theme: [default, custom.scss]

format:
  revealjs:
    logo: images/HITS_RGB_eng.jpg
    footer: "ML Workflow Orchestration (Bernd Doser, HITS)"
    slide-number: true
    highlight-style: a11y
    code-block-height: 650px
    # width: 1300
